### ISSUE TITLE
AttributeError: module 'theano.tensor.nlinalg' has no attribute 'LogDetPSD'

### ISSUE THREAD

**Issue by Jthy-af** [Bibyutatsu/FastJTNNpy3#1]
This error occurred while I was running the code，I couldn't find the solution on the Internet. I hope I successfully installed Theano(because I'm not sure)：
UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Initializing network
WARNING (theano.gof.compilelock): Overriding existing lock by dead process '17108' (I am process '11780')
Traceback (most recent call last):
  File "F:/Study/YJS/FastJTNNpy3-master/fast_bo/run_bo.py", line 248, in <module>
    random_seed)
  File "F:/Study/YJS/FastJTNNpy3-master/fast_bo/run_bo.py", line 112, in main_bo
    learning_rate=0.001)
  File "F:\Study\YJS\FastJTNNpy3-master\fast_jtnn\sparse_gp.py", line 209, in train_via_ADAM
    e = self.getEnergy()
  File "F:\Study\YJS\FastJTNNpy3-master\fast_jtnn\sparse_gp.py", line 99, in getEnergy
    return self.sparse_gp.getContributionToEnergy()[ 0, 0 ]
  File "F:\Study\YJS\FastJTNNpy3-master\fast_jtnn\sparse_gp_theano_internal.py", line 191, in getContributionToEnergy
    logZpost = self.getLogNormalizerPosterior()
  File "F:\Study\YJS\FastJTNNpy3-master\fast_jtnn\sparse_gp_theano_internal.py", line 180, in getLogNormalizerPosterior
    return casting(0.5 * self.n_inducing_points * np.log(2 * np.pi)) + casting(0.5) * T.nlinalg.LogDetPSD()(self.covPosterior) + \
AttributeError: module 'theano.tensor.nlinalg' has no attribute 'LogDetPSD'

**Comment by Bibyutatsu** [comment]
Hi,
Yeah you need to install the custom Theano library as instructed [here](https://github.com/Bibyutatsu/FastJTNNpy3/blob/master/fast_bo/README.md).

If you have installed the theano using `pip install theano` you need to uninstall it and follow the instructions:
1. `git clone https://github.com/mkusner/grammarVAE.git`
2. `cd Theano-master`
3. `python setup.py install`

**Comment by Jthy-af** [comment]
@Bibyutatsu Wow, that's great! My code is finally running! The problem that had been bothering me for weeks was finally solved. I really appreciate your help!!

**Comment by Bibyutatsu** [comment]
@Jthy-af glad to help you.

I am closing this issue, feel free to open if you face any problem.
